services:
  # Python (Flask) service for machine learning predictions and frontend
  - type: web
    name: hemotouch-python-api
    env: python
    # Ensure this is the correct path to your Python app
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      # Add the URL of your Node API once it's deployed
      - key: API_URL
        value: "" # Will be something like https://hemotouch-node-api.onrender.com
      - key: PREDICT_API_URL
        value: "" # This will be the URL of this service itself

  # Node.js service for database interactions
  - type: web
    name: hemotouch-node-api
    env: node
    # Ensure this is the correct path to your Node.js app
    rootDir: .
    buildCommand: "npm install"
    startCommand: "node api.js"
    envVars:
      - key: DATABASE_URL
        # This tells Render to use the secret you'll create in the dashboard
        sync: false